version: '2'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
     - '27017:27017'

  vault:
    image: sjourdan/vault
    container_name: vault
    hostname: vault
    ports:
     - '8200:8200'

networks:
  default:
    external:
      name: local